-- ============================================================================
-- 100 — Kai Integration: AI research reports + "Ask Kai" chat.
--
-- Two features, one persona (Kai, CheatCode's AI analyst). Education-first
-- posture matches the /help bot: research/analysis/teaching only, no
-- personalized buy/sell advice, age-aware register for kid accounts.
--
-- RLS posture (matches the repo scars):
--   * kai_reports — any authenticated member READS (free tier gated in-app via
--     UpsellCard, never queried here). No member write policy: reports are
--     generated by the admin-gated server route using the service role, which
--     bypasses RLS. Provenance (generated_by/model/version) recorded per row.
--   * kai_chat_threads / kai_chat_messages — strict OWN-ROW SELECT + INSERT +
--     DELETE keyed on auth.uid(). A member only ever sees their own chat.
--     No Realtime on any of these tables.
--   * Rate caps are enforced in the /kai SSE route (service role counts the
--     member's user-role messages for the day); not an RLS concern.
-- ============================================================================

-- ── 1. kai_reports — versioned, admin-generated research reports per ticker ──
create table if not exists kai_reports (
  id            uuid primary key default gen_random_uuid(),
  ticker        text not null,
  company_name  text,
  version       integer not null default 1,
  status        text not null default 'published'
                  check (status in ('draft', 'published', 'archived')),
  model         text,                 -- provenance: which model wrote it
  sections      jsonb not null,       -- model-written prose sections (see route)
  data          jsonb not null default '{}'::jsonb,  -- bars/financials/quote for charts
  generated_by  uuid references profiles(id) on delete set null,
  generated_at  timestamptz not null default now(),
  created_at    timestamptz not null default now()
);

-- One report per (ticker, version); newest published wins in the member view.
create unique index if not exists uq_kai_reports_ticker_version
  on kai_reports(upper(ticker), version);
create index if not exists idx_kai_reports_ticker
  on kai_reports(upper(ticker), version desc);
create index if not exists idx_kai_reports_status
  on kai_reports(status);

alter table kai_reports enable row level security;

-- Read: any authenticated member (free tier hits UpsellCard in the UI).
drop policy if exists "Read kai reports" on kai_reports;
create policy "Read kai reports" on kai_reports
  for select to authenticated using (true);
-- No INSERT/UPDATE/DELETE policy: generation is service-role only.

-- ── 2. kai_chat_threads — one row per Ask Kai conversation ────────────────────
create table if not exists kai_chat_threads (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references profiles(id) on delete cascade,
  title      text not null default 'New chat',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists idx_kai_threads_user
  on kai_chat_threads(user_id, updated_at desc);

create or replace function public.kai_threads_touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end;
$$;
drop trigger if exists trg_kai_threads_touch on kai_chat_threads;
create trigger trg_kai_threads_touch
  before update on kai_chat_threads
  for each row execute function public.kai_threads_touch_updated_at();

alter table kai_chat_threads enable row level security;

drop policy if exists "Own kai threads select" on kai_chat_threads;
create policy "Own kai threads select" on kai_chat_threads
  for select to authenticated using (user_id = auth.uid());

drop policy if exists "Own kai threads insert" on kai_chat_threads;
create policy "Own kai threads insert" on kai_chat_threads
  for insert to authenticated with check (user_id = auth.uid());

drop policy if exists "Own kai threads update" on kai_chat_threads;
create policy "Own kai threads update" on kai_chat_threads
  for update to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "Own kai threads delete" on kai_chat_threads;
create policy "Own kai threads delete" on kai_chat_threads
  for delete to authenticated using (user_id = auth.uid());

-- ── 3. kai_chat_messages — turns within a thread ─────────────────────────────
-- `blocks` carries structured render payloads the assistant produced this turn:
-- inline chart data blocks ({kind:'chart', symbol, bars}) and news link cards
-- ({kind:'news', items:[...]}). The plain `content` is the markdown answer text.
create table if not exists kai_chat_messages (
  id         uuid primary key default gen_random_uuid(),
  thread_id  uuid not null references kai_chat_threads(id) on delete cascade,
  user_id    uuid not null references profiles(id) on delete cascade,
  role       text not null check (role in ('user', 'assistant')),
  content    text not null default '',
  blocks     jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists idx_kai_messages_thread
  on kai_chat_messages(thread_id, created_at);
create index if not exists idx_kai_messages_user_day
  on kai_chat_messages(user_id, created_at);

alter table kai_chat_messages enable row level security;

drop policy if exists "Own kai messages select" on kai_chat_messages;
create policy "Own kai messages select" on kai_chat_messages
  for select to authenticated using (user_id = auth.uid());

drop policy if exists "Own kai messages insert" on kai_chat_messages;
create policy "Own kai messages insert" on kai_chat_messages
  for insert to authenticated
  with check (
    user_id = auth.uid()
    and exists (
      select 1 from kai_chat_threads t
      where t.id = thread_id and t.user_id = auth.uid()
    )
  );

drop policy if exists "Own kai messages delete" on kai_chat_messages;
create policy "Own kai messages delete" on kai_chat_messages
  for delete to authenticated using (user_id = auth.uid());

-- ── 4. get_latest_kai_report(ticker) — one round-trip member read ────────────
-- SECURITY INVOKER: relies on the "Read kai reports" policy (true), so it stays
-- consistent with the app-gating posture. Returns the newest PUBLISHED version.
create or replace function public.get_latest_kai_report(p_ticker text)
returns jsonb
language sql
stable
security invoker
set search_path = public
as $$
  select to_jsonb(r) from kai_reports r
  where upper(r.ticker) = upper(p_ticker) and r.status = 'published'
  order by r.version desc
  limit 1;
$$;
grant execute on function public.get_latest_kai_report(text) to authenticated;

-- ── 5. next_kai_report_version(ticker) — versioning helper for the generator ──
-- SECURITY DEFINER so the admin route (service role already bypasses RLS, but
-- this keeps the increment atomic + reusable) resolves the next version number.
create or replace function public.next_kai_report_version(p_ticker text)
returns integer
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(max(version), 0) + 1 from kai_reports
  where upper(ticker) = upper(p_ticker);
$$;
grant execute on function public.next_kai_report_version(text) to authenticated;
