-- 206 — PILOT LESSON, AUDIO-FIRST.
--
-- ═══════════════════════════════════════════════════════════════════════════
-- The owner rejected the text-heavy pilot outright: "it should be audio
-- speaking the words with images or animations or interactions on screen, not
-- read like a book — again we are going for duolingo experience."
--
-- This migration replaces the PRESENTATION of the Day 3 pilot and nothing else.
-- Same eight steps, same ids, same questions, same correct answers, same skills,
-- same 50 XP, same lesson row. Not one member's lesson_progress, quiz_attempts
-- or xp_events row changes meaning, because none of the things those reference
-- moved. What changed is inside `steps`:
--
--   • Each explainer now carries a `beats` array — the SAME approved prose,
--     split on sentence boundaries into 1–3 sentence spoken beats, each with
--     the visual state that holds while it is spoken. The generator refuses to
--     write this file unless every beat is a verbatim slice of the paragraph it
--     came from, so the curriculum voice can be split but never rewritten.
--   • Every line that can reach a member's ears — question prompts, per-option
--     wrong feedback, reinforcements, the re-ask, the reveal walk-up, the guide
--     lines, the real-world instruction, the intro and the outro — carries an
--     `audio` entry: { url, durationMs, say }.
--
-- THE AUDIO IS STATIC. Pre-generated by scripts/build-lesson-audio.mjs with
-- Voicebox, the local MLX voice server, profile "Kway"
-- (2cd42fda-3482-4eb4-a79a-6abc64802e24) — the same voice the reels use — and
-- served from
-- /lessons/audio/adult-d03/*.mp3. There is NO runtime TTS and no LLM anywhere
-- in this path: what a member hears is a published artifact, identical for
-- everyone, forever — the same promise the hand-written prices make.
--
-- Compliance rails unchanged: education, never advice; equities only; no
-- performance claims; every price hand-written and dated illustrative
-- (NKE, 2025-Q3), never a live quote.
--
-- GUARDED + IDEMPOTENT. It updates exactly one row, by id, and only if that row
-- is still the pilot; re-running is a no-op. A rollback is re-applying 202.
--
-- Generated by: node scripts/build-pilot-lesson.mjs --audio-migration
-- Do NOT hand-edit the JSON below — edit the typed module and regenerate.
--
-- ═══════════════════════════════════════════════════════════════════════════

update lessons
set
  steps       = $json$
{
  "schema": 1,
  "title": "Why the price moves at all",
  "skills": [
    "market_basics",
    "stock_ownership"
  ],
  "difficulty": 2,
  "audience": [
    "adult"
  ],
  "duration_minutes": 7,
  "xp": 50,
  "guide": {
    "intro": "Most people picture a stock price like a price tag — somebody decided it, printed it, done. That picture is wrong, and it quietly costs people money. Give me seven minutes and you'll never look at a quote the same way.",
    "outro": "You now know what's under every price move you'll ever see. Everything later in this course — where to put a stop, why a great quarter can tank a stock, what selling in pieces actually does — is just these two lines rearranging. Tomorrow we set up your workshop: which account to use, and why the answer depends on when you need the money, not what you're buying."
  },
  "steps": [
    {
      "id": "a-d03-warm",
      "type": "multiple_choice",
      "skill": "revenue",
      "question": "Yesterday: a company's revenue is just everything customers bought from it. So when Costco reports revenue for a quarter, whose money is that?",
      "options": [
        "Investors who bought Costco stock",
        "Shoppers who bought stuff at Costco",
        "Money Costco borrowed from a bank",
        "Money from Costco selling one of its buildings"
      ],
      "correctIndex": 1,
      "reinforce": "Yep. Revenue is customers, full stop. When investors buy shares, that money goes to whoever sold them — it never touches the company.",
      "explanation": "Revenue is customers, full stop — money from people at the register. Anything else the company takes in is something other than revenue.",
      "wrongFeedback": [
        {
          "kai": true,
          "text": "This one trips up almost everybody at first, so it's worth nailing down. When you buy a share, your money goes to the person who sold it to you. Another investor, somewhere. The company doesn't see a dime of it. Revenue is people at the register. Let's take that one again."
        },
        null,
        {
          "text": "Borrowed money isn't revenue — it's debt. Money you have to give back was never earned."
        },
        {
          "text": "Selling a building is a one-off. Revenue is what customers pay for what the company actually sells."
        }
      ],
      "audio": {
        "prompt": {
          "url": "/lessons/audio/adult-d03/a-d03-warm.mp3",
          "durationMs": 10240,
          "say": "Yesterday: a company's revenue is just everything customers bought from it. So when Costco reports revenue for a quarter, whose money is that?"
        },
        "reinforce": {
          "url": "/lessons/audio/adult-d03/a-d03-warm-reinforce.mp3",
          "durationMs": 8240,
          "say": "Yep. Revenue is customers, full stop. When investors buy shares, that money goes to whoever sold them — it never touches the company."
        },
        "explanation": {
          "url": "/lessons/audio/adult-d03/a-d03-warm-explanation.mp3",
          "durationMs": 10800,
          "say": "Revenue is customers, full stop — money from people at the register. Anything else the company takes in is something other than revenue."
        },
        "wrong:0": {
          "url": "/lessons/audio/adult-d03/a-d03-warm-wrong-0.mp3",
          "durationMs": 18240,
          "say": "This one trips up almost everybody at first, so it's worth nailing down. When you buy a share, your money goes to the person who sold it to you. Another investor, somewhere. The company doesn't see a dime of it. Revenue is people at the register. Let's take that one again."
        },
        "wrong:2": {
          "url": "/lessons/audio/adult-d03/a-d03-warm-wrong-2.mp3",
          "durationMs": 5200,
          "say": "Borrowed money isn't revenue — it's debt. Money you have to give back was never earned."
        },
        "wrong:3": {
          "url": "/lessons/audio/adult-d03/a-d03-warm-wrong-3.mp3",
          "durationMs": 8000,
          "say": "Selling a building is a one-off. Revenue is what customers pay for what the company actually sells."
        },
        "reask": {
          "url": "/lessons/audio/adult-d03/a-d03-warm-reask.mp3",
          "durationMs": 1520,
          "say": "Let's try that again."
        }
      }
    },
    {
      "id": "a-d03-x1",
      "type": "explainer",
      "skill": "market_basics",
      "heading": "Nobody actually sets the price",
      "body": [
        "You open your app, it says Nike is $74.20, and it's natural to assume somebody decided that. Someone at the company. Someone at the exchange. Someone in a suit.",
        "Nope. Nike has zero say in what its stock costs. Neither does the app. Neither does the exchange.",
        "What actually exists is two lines of people. On one side, everybody who wants to buy has said the most they'll pay. On the other, everybody willing to sell has said the least they'll take. The best offer from the buyers is called the bid. The best one from the sellers is the ask. They're never the same number, because nobody volunteers to pay more than they have to.",
        "Think of a garage sale where thirty people are haggling at once. That's it. That's the stock market.",
        "A trade happens the moment somebody gives in. A buyer who wants it now agrees to pay the ask. A seller who wants out now takes the bid. That's a trade, and the price it happened at is the number on your screen. The quote isn't a price. It's a receipt from the last person who stopped waiting."
      ],
      "figure": {
        "kind": "stat",
        "value": "$74.18 / $74.22",
        "caption": "bid / ask — the two lines, and the 4¢ between them"
      },
      "illustration": {
        "kind": "order_book",
        "mode": "ladder",
        "bids": [
          "74.18",
          "74.15",
          "74.11",
          "74.04"
        ],
        "asks": [
          "74.22",
          "74.26",
          "74.31",
          "74.40"
        ],
        "spreadLabel": "the spread",
        "caption": "NKE · illustrative levels, 2025-Q3 — not a live quote"
      },
      "beats": [
        {
          "id": "b1",
          "say": "You open your app, it says Nike is $74.20, and it's natural to assume somebody decided that. Someone at the company. Someone at the exchange. Someone in a suit.",
          "headline": "Somebody decided this. Right?",
          "key": {
            "value": "$74.20",
            "caption": "Nike, on your screen"
          },
          "audio": {
            "url": "/lessons/audio/adult-d03/a-d03-x1-b1.mp3",
            "durationMs": 12880,
            "say": "You open your app, it says Nike is $74.20, and it's natural to assume somebody decided that. Someone at the company. Someone at the exchange. Someone in a suit."
          }
        },
        {
          "id": "b2",
          "say": "Nope. Nike has zero say in what its stock costs. Neither does the app. Neither does the exchange.",
          "headline": "Nobody.",
          "key": {
            "value": "$74.20",
            "caption": "Nike, on your screen"
          },
          "audio": {
            "url": "/lessons/audio/adult-d03/a-d03-x1-b2.mp3",
            "durationMs": 8080,
            "say": "Nope. Nike has zero say in what its stock costs. Neither does the app. Neither does the exchange."
          }
        },
        {
          "id": "b3",
          "say": "What actually exists is two lines of people. On one side, everybody who wants to buy has said the most they'll pay. On the other, everybody willing to sell has said the least they'll take.",
          "headline": "Two lines of people",
          "illustration": {
            "kind": "order_book",
            "mode": "ladder",
            "bids": [
              "74.18",
              "74.15",
              "74.11",
              "74.04"
            ],
            "asks": [
              "74.22",
              "74.26",
              "74.31",
              "74.40"
            ],
            "showSpread": false,
            "caption": "NKE · illustrative levels, 2025-Q3 — not a live quote"
          },
          "audio": {
            "url": "/lessons/audio/adult-d03/a-d03-x1-b3.mp3",
            "durationMs": 11680,
            "say": "What actually exists is two lines of people. On one side, everybody who wants to buy has said the most they'll pay. On the other, everybody willing to sell has said the least they'll take."
          }
        },
        {
          "id": "b4",
          "say": "The best offer from the buyers is called the bid. The best one from the sellers is the ask. They're never the same number, because nobody volunteers to pay more than they have to.",
          "headline": "bid · ask",
          "illustration": {
            "kind": "order_book",
            "mode": "ladder",
            "bids": [
              "74.18",
              "74.15",
              "74.11",
              "74.04"
            ],
            "asks": [
              "74.22",
              "74.26",
              "74.31",
              "74.40"
            ],
            "spreadLabel": "the spread",
            "caption": "NKE · illustrative levels, 2025-Q3 — not a live quote"
          },
          "audio": {
            "url": "/lessons/audio/adult-d03/a-d03-x1-b4.mp3",
            "durationMs": 12000,
            "say": "The best offer from the buyers is called the bid. The best one from the sellers is the ask. They're never the same number, because nobody volunteers to pay more than they have to."
          }
        },
        {
          "id": "b5",
          "say": "Think of a garage sale where thirty people are haggling at once. That's it. That's the stock market.",
          "headline": "A garage sale, thirty people deep.",
          "illustration": {
            "kind": "order_book",
            "mode": "ladder",
            "bids": [
              "74.18",
              "74.15",
              "74.11",
              "74.04"
            ],
            "asks": [
              "74.22",
              "74.26",
              "74.31",
              "74.40"
            ],
            "spreadLabel": "the spread",
            "caption": "NKE · illustrative levels, 2025-Q3 — not a live quote"
          },
          "audio": {
            "url": "/lessons/audio/adult-d03/a-d03-x1-b5.mp3",
            "durationMs": 10160,
            "say": "Think of a garage sale where thirty people are haggling at once. That's it. That's the stock market."
          }
        },
        {
          "id": "b6",
          "say": "A trade happens the moment somebody gives in. A buyer who wants it now agrees to pay the ask. A seller who wants out now takes the bid.",
          "headline": "A trade is somebody giving in.",
          "key": {
            "value": "$74.18 / $74.22",
            "caption": "bid / ask — 4¢ apart"
          },
          "illustration": {
            "kind": "order_book",
            "mode": "ladder",
            "bids": [
              "74.18",
              "74.15",
              "74.11",
              "74.04"
            ],
            "asks": [
              "74.22",
              "74.26",
              "74.31",
              "74.40"
            ],
            "spreadLabel": "the spread",
            "caption": "NKE · illustrative levels, 2025-Q3 — not a live quote"
          },
          "audio": {
            "url": "/lessons/audio/adult-d03/a-d03-x1-b6.mp3",
            "durationMs": 9360,
            "say": "A trade happens the moment somebody gives in. A buyer who wants it now agrees to pay the ask. A seller who wants out now takes the bid."
          }
        },
        {
          "id": "b7",
          "say": "That's a trade, and the price it happened at is the number on your screen. The quote isn't a price. It's a receipt from the last person who stopped waiting.",
          "headline": "The quote is a receipt.",
          "key": {
            "value": "$74.18 / $74.22",
            "caption": "bid / ask — 4¢ apart"
          },
          "illustration": {
            "kind": "order_book",
            "mode": "ladder",
            "bids": [
              "74.18",
              "74.15",
              "74.11",
              "74.04"
            ],
            "asks": [
              "74.22",
              "74.26",
              "74.31",
              "74.40"
            ],
            "spreadLabel": "the spread",
            "caption": "NKE · illustrative levels, 2025-Q3 — not a live quote"
          },
          "audio": {
            "url": "/lessons/audio/adult-d03/a-d03-x1-b7.mp3",
            "durationMs": 8720,
            "say": "That's a trade, and the price it happened at is the number on your screen. The quote isn't a price. It's a receipt from the last person who stopped waiting."
          }
        }
      ]
    },
    {
      "id": "a-d03-pred",
      "type": "prediction",
      "skill": "market_basics",
      "question": "A fund manager decides to buy 500,000 shares of Nike, right now, at whatever it takes. The ask is $74.22 — but only 12,000 shares are being offered at that price. What happens?",
      "options": [
        {
          "label": "She gets all 500,000 at $74.22 — that's the price on the screen",
          "value": "at_ask"
        },
        {
          "label": "She takes the 12,000, then pays more and more as she works her way up the line",
          "value": "walks_up"
        },
        {
          "label": "The order gets rejected — there aren't enough shares",
          "value": "rejected"
        },
        {
          "label": "The price drops, because an order that big makes people nervous",
          "value": "falls"
        }
      ],
      "outcomeValue": "walks_up",
      "illustration": {
        "kind": "order_book",
        "mode": "walk_up",
        "bids": [
          "74.18",
          "74.15",
          "74.11",
          "74.04"
        ],
        "asks": [
          "74.22",
          "74.26",
          "74.31",
          "74.40"
        ],
        "spreadLabel": "the spread",
        "walkPrices": [
          "$74.22",
          "$74.26",
          "$74.31",
          "$74.40"
        ],
        "caption": "NKE · illustrative levels, 2025-Q3 — not a live quote"
      },
      "reveal": {
        "headline": "She works her way up the line — and pushes the price up doing it.",
        "body": "She takes the 12,000 at $74.22. Now the cheapest shares left are at $74.26, so she takes those. Then $74.31. Then $74.40. By the time she's got her 500,000 she's paid way more on average than she started at — and the price everybody else now sees is $74.40. She moved it.\n\nNow notice what didn't happen. No news. No announcement. Nothing about Nike's business changed between $74.22 and $74.40. The price went up because one buyer wanted more shares than anyone was selling at that price, and the only way to get them was to pay up.\n\nThat's the whole thing. Every price move you'll ever see is some version of this.",
        "scene": {
          "kind": "price_event",
          "caption": "the tape while she filled",
          "points": [
            0.16,
            0.13,
            0.19,
            0.15,
            0.2,
            0.44,
            0.66,
            1
          ],
          "eventIndex": 4,
          "eventLabel": "500K BUY",
          "endLabel": "$74.40"
        }
      },
      "guideOn": {
        "value": "falls",
        "line": "That's actually the smartest wrong answer, so it's worth a minute. Big orders do sometimes tell people something, and traders watch for exactly that. But before anyone gets around to reading into it, the buying has to physically get absorbed — and absorbing buying means paying up. The mechanics happen first. The meaning comes later."
      },
      "audio": {
        "prompt": {
          "url": "/lessons/audio/adult-d03/a-d03-pred.mp3",
          "durationMs": 15360,
          "say": "A fund manager decides to buy 500,000 shares of Nike, right now, at whatever it takes. The ask is $74.22 — but only 12,000 shares are being offered at that price. What happens?"
        },
        "reveal:0": {
          "url": "/lessons/audio/adult-d03/a-d03-pred-reveal-0.mp3",
          "durationMs": 5040,
          "say": "She works her way up the line — and pushes the price up doing it."
        },
        "reveal:1": {
          "url": "/lessons/audio/adult-d03/a-d03-pred-reveal-1.mp3",
          "durationMs": 24240,
          "say": "She takes the 12,000 at $74.22. Now the cheapest shares left are at $74.26, so she takes those. Then $74.31. Then $74.40. By the time she's got her 500,000 she's paid way more on average than she started at — and the price everybody else now sees is $74.40. She moved it."
        },
        "reveal:2": {
          "url": "/lessons/audio/adult-d03/a-d03-pred-reveal-2.mp3",
          "durationMs": 17360,
          "say": "Now notice what didn't happen. No news. No announcement. Nothing about Nike's business changed between $74.22 and $74.40. The price went up because one buyer wanted more shares than anyone was selling at that price, and the only way to get them was to pay up."
        },
        "reveal:3": {
          "url": "/lessons/audio/adult-d03/a-d03-pred-reveal-3.mp3",
          "durationMs": 5920,
          "say": "That's the whole thing. Every price move you'll ever see is some version of this."
        },
        "guide:falls": {
          "url": "/lessons/audio/adult-d03/a-d03-pred-guide-falls.mp3",
          "durationMs": 20240,
          "say": "That's actually the smartest wrong answer, so it's worth a minute. Big orders do sometimes tell people something, and traders watch for exactly that. But before anyone gets around to reading into it, the buying has to physically get absorbed — and absorbing buying means paying up. The mechanics happen first. The meaning comes later."
        },
        "guide:correct": {
          "url": "/lessons/audio/adult-d03/a-d03-pred-guide-correct.mp3",
          "durationMs": 3440,
          "say": "You called it. That's the read of an investor."
        },
        "guide:wrong": {
          "url": "/lessons/audio/adult-d03/a-d03-pred-guide-wrong.mp3",
          "durationMs": 3680,
          "say": "Not the call you made — and that's exactly how you learn to read one."
        }
      }
    },
    {
      "id": "a-d03-x2",
      "type": "explainer",
      "skill": "market_basics",
      "heading": "So where does news fit in?",
      "body": [
        "If prices move because of who's buying and selling at each price, what does news do? It doesn't move the price directly. It changes what people put in the two lines.",
        "Good news comes out. Buyers who were happy waiting at $74.18 now think it's worth more, so they cancel and come back at $75.40. Sellers who were fine letting go at $74.22 pull their offers — why sell at yesterday's price? The buying line goes up, the selling line thins out, and the next trade happens way higher.",
        "Nobody announced a new price. The two lines just rebuilt themselves around a new opinion.",
        "This is why people say news is “already priced in.” It's not a saying. It's just what happened while you were reading the headline. By the time you see it, the people who moved first have already rearranged both lines. You're not looking at the price before the news. You're looking at the price after a few thousand people finished arguing about it."
      ],
      "illustration": {
        "kind": "order_book",
        "mode": "before_after",
        "bids": [
          "74.18",
          "74.15",
          "74.11",
          "74.04"
        ],
        "asks": [
          "74.22",
          "74.26",
          "74.31",
          "74.40"
        ],
        "beforeLabel": "before",
        "spreadLabel": "the spread",
        "after": {
          "bids": [
            "75.40",
            "75.34",
            "75.28",
            "75.19"
          ],
          "asks": [
            "76.05",
            "76.60"
          ],
          "label": "after"
        },
        "caption": "The same drawing, one variable changed — sellers pulled."
      },
      "beats": [
        {
          "id": "b1",
          "say": "If prices move because of who's buying and selling at each price, what does news do? It doesn't move the price directly. It changes what people put in the two lines.",
          "headline": "News doesn't move the price.",
          "illustration": {
            "kind": "order_book",
            "mode": "ladder",
            "bids": [
              "74.18",
              "74.15",
              "74.11",
              "74.04"
            ],
            "asks": [
              "74.22",
              "74.26",
              "74.31",
              "74.40"
            ],
            "spreadLabel": "the spread",
            "caption": "NKE · illustrative levels, 2025-Q3 — not a live quote"
          },
          "audio": {
            "url": "/lessons/audio/adult-d03/a-d03-x2-b1.mp3",
            "durationMs": 10560,
            "say": "If prices move because of who's buying and selling at each price, what does news do? It doesn't move the price directly. It changes what people put in the two lines."
          }
        },
        {
          "id": "b2",
          "say": "Good news comes out. Buyers who were happy waiting at $74.18 now think it's worth more, so they cancel and come back at $75.40.",
          "headline": "Buyers come back higher.",
          "illustration": {
            "kind": "order_book",
            "mode": "ladder",
            "bids": [
              "74.18",
              "74.15",
              "74.11",
              "74.04"
            ],
            "asks": [
              "74.22",
              "74.26",
              "74.31",
              "74.40"
            ],
            "spreadLabel": "the spread",
            "caption": "NKE · illustrative levels, 2025-Q3 — not a live quote"
          },
          "audio": {
            "url": "/lessons/audio/adult-d03/a-d03-x2-b2.mp3",
            "durationMs": 11440,
            "say": "Good news comes out. Buyers who were happy waiting at $74.18 now think it's worth more, so they cancel and come back at $75.40."
          }
        },
        {
          "id": "b3",
          "say": "Sellers who were fine letting go at $74.22 pull their offers — why sell at yesterday's price? The buying line goes up, the selling line thins out, and the next trade happens way higher.",
          "headline": "Sellers pull.",
          "illustration": {
            "kind": "order_book",
            "mode": "before_after",
            "bids": [
              "74.18",
              "74.15",
              "74.11",
              "74.04"
            ],
            "asks": [
              "74.22",
              "74.26",
              "74.31",
              "74.40"
            ],
            "beforeLabel": "before",
            "spreadLabel": "the spread",
            "after": {
              "bids": [
                "75.40",
                "75.34",
                "75.28",
                "75.19"
              ],
              "asks": [
                "76.05",
                "76.60"
              ],
              "label": "after"
            },
            "caption": "The same drawing, one variable changed — sellers pulled."
          },
          "audio": {
            "url": "/lessons/audio/adult-d03/a-d03-x2-b3.mp3",
            "durationMs": 15680,
            "say": "Sellers who were fine letting go at $74.22 pull their offers — why sell at yesterday's price? The buying line goes up, the selling line thins out, and the next trade happens way higher."
          }
        },
        {
          "id": "b4",
          "say": "Nobody announced a new price. The two lines just rebuilt themselves around a new opinion.",
          "headline": "The lines rebuilt themselves.",
          "illustration": {
            "kind": "order_book",
            "mode": "before_after",
            "bids": [
              "74.18",
              "74.15",
              "74.11",
              "74.04"
            ],
            "asks": [
              "74.22",
              "74.26",
              "74.31",
              "74.40"
            ],
            "beforeLabel": "before",
            "spreadLabel": "the spread",
            "after": {
              "bids": [
                "75.40",
                "75.34",
                "75.28",
                "75.19"
              ],
              "asks": [
                "76.05",
                "76.60"
              ],
              "label": "after"
            },
            "caption": "The same drawing, one variable changed — sellers pulled."
          },
          "audio": {
            "url": "/lessons/audio/adult-d03/a-d03-x2-b4.mp3",
            "durationMs": 7120,
            "say": "Nobody announced a new price. The two lines just rebuilt themselves around a new opinion."
          }
        },
        {
          "id": "b5",
          "say": "This is why people say news is “already priced in.” It's not a saying. It's just what happened while you were reading the headline.",
          "headline": "“Already priced in.”",
          "illustration": {
            "kind": "order_book",
            "mode": "before_after",
            "bids": [
              "74.18",
              "74.15",
              "74.11",
              "74.04"
            ],
            "asks": [
              "74.22",
              "74.26",
              "74.31",
              "74.40"
            ],
            "beforeLabel": "before",
            "spreadLabel": "the spread",
            "after": {
              "bids": [
                "75.40",
                "75.34",
                "75.28",
                "75.19"
              ],
              "asks": [
                "76.05",
                "76.60"
              ],
              "label": "after"
            },
            "caption": "The same drawing, one variable changed — sellers pulled."
          },
          "audio": {
            "url": "/lessons/audio/adult-d03/a-d03-x2-b5.mp3",
            "durationMs": 7200,
            "say": "This is why people say news is “already priced in.” It's not a saying. It's just what happened while you were reading the headline."
          }
        },
        {
          "id": "b6",
          "say": "By the time you see it, the people who moved first have already rearranged both lines. You're not looking at the price before the news. You're looking at the price after a few thousand people finished arguing about it.",
          "headline": "You're seeing the price after the argument.",
          "illustration": {
            "kind": "order_book",
            "mode": "before_after",
            "bids": [
              "74.18",
              "74.15",
              "74.11",
              "74.04"
            ],
            "asks": [
              "74.22",
              "74.26",
              "74.31",
              "74.40"
            ],
            "beforeLabel": "before",
            "spreadLabel": "the spread",
            "after": {
              "bids": [
                "75.40",
                "75.34",
                "75.28",
                "75.19"
              ],
              "asks": [
                "76.05",
                "76.60"
              ],
              "label": "after"
            },
            "caption": "The same drawing, one variable changed — sellers pulled."
          },
          "audio": {
            "url": "/lessons/audio/adult-d03/a-d03-x2-b6.mp3",
            "durationMs": 11680,
            "say": "By the time you see it, the people who moved first have already rearranged both lines. You're not looking at the price before the news. You're looking at the price after a few thousand people finished arguing about it."
          }
        }
      ]
    },
    {
      "id": "a-d03-mc1",
      "type": "multiple_choice",
      "skill": "market_basics",
      "framing": "spread",
      "question": "The bid on a stock is $28.40 and the ask is $29.15. What's that spread telling you?",
      "options": [
        "The stock is about to drop 75 cents",
        "Buyers and sellers are 75 cents apart on what it's worth",
        "Someone charges 75 cents to trade it",
        "The stock went up 75 cents today"
      ],
      "correctIndex": 1,
      "reinforce": "That's it. A wide spread is two groups of people disagreeing out loud. It's also a cost — buy at $29.15, sell a second later at $28.40, and you're down 75 cents without doing anything wrong.",
      "explanation": "A spread is the distance between two live opinions, not a move that already happened.",
      "wrongFeedback": [
        {
          "kai": true,
          "text": "There's no direction in a spread. It's the distance between two opinions, not an arrow. A stock can sit with a 75-cent spread all day and close exactly where it opened. One more go."
        },
        null,
        {
          "text": "Fair guess, and there's something to it — the spread really is a cost you pay. But nobody's charging it. It's just the gap you jump across when you're the one in a hurry."
        },
        {
          "text": "That's a move, not a gap. The spread is two prices sitting side by side right now, not the distance the stock travelled today."
        }
      ],
      "audio": {
        "prompt": {
          "url": "/lessons/audio/adult-d03/a-d03-mc1.mp3",
          "durationMs": 9200,
          "say": "The bid on a stock is $28.40 and the ask is $29.15. What's that spread telling you?"
        },
        "reinforce": {
          "url": "/lessons/audio/adult-d03/a-d03-mc1-reinforce.mp3",
          "durationMs": 15680,
          "say": "That's it. A wide spread is two groups of people disagreeing out loud. It's also a cost — buy at $29.15, sell a second later at $28.40, and you're down 75 cents without doing anything wrong."
        },
        "explanation": {
          "url": "/lessons/audio/adult-d03/a-d03-mc1-explanation.mp3",
          "durationMs": 5680,
          "say": "A spread is the distance between two live opinions, not a move that already happened."
        },
        "wrong:0": {
          "url": "/lessons/audio/adult-d03/a-d03-mc1-wrong-0.mp3",
          "durationMs": 12320,
          "say": "There's no direction in a spread. It's the distance between two opinions, not an arrow. A stock can sit with a 75-cent spread all day and close exactly where it opened. One more go."
        },
        "wrong:2": {
          "url": "/lessons/audio/adult-d03/a-d03-mc1-wrong-2.mp3",
          "durationMs": 10160,
          "say": "Fair guess, and there's something to it — the spread really is a cost you pay. But nobody's charging it. It's just the gap you jump across when you're the one in a hurry."
        },
        "wrong:3": {
          "url": "/lessons/audio/adult-d03/a-d03-mc1-wrong-3.mp3",
          "durationMs": 8720,
          "say": "That's a move, not a gap. The spread is two prices sitting side by side right now, not the distance the stock travelled today."
        },
        "reask": {
          "url": "/lessons/audio/adult-d03/a-d03-mc1-reask.mp3",
          "durationMs": 1520,
          "say": "Let's try that again."
        }
      }
    },
    {
      "id": "a-d03-tf",
      "type": "true_false",
      "skill": "market_basics",
      "trueLabel": "Fact",
      "falseLabel": "Myth",
      "statement": "“The price I see on my screen is the price my next order will get.”",
      "answer": false,
      "explanation": "That price is a record of a trade that already happened — maybe seconds ago, maybe minutes ago. Your order shows up and meets whatever line exists right then. If you're buying in a hurry, you pay the ask, which is higher. If you're selling in a hurry, you get the bid, which is lower. On a big, busy stock that's pennies. On a quiet one, it really isn't.",
      "reinforce": "Exactly — and here's the kicker. That big number on your screen is the least useful of the three. The bid and ask tell you what's actually available right now. The last trade only tells you what somebody already did.",
      "audio": {
        "prompt": {
          "url": "/lessons/audio/adult-d03/a-d03-tf.mp3",
          "durationMs": 4080,
          "say": "“The price I see on my screen is the price my next order will get.”"
        },
        "reinforce": {
          "url": "/lessons/audio/adult-d03/a-d03-tf-reinforce.mp3",
          "durationMs": 13280,
          "say": "Exactly — and here's the kicker. That big number on your screen is the least useful of the three. The bid and ask tell you what's actually available right now. The last trade only tells you what somebody already did."
        },
        "explanation": {
          "url": "/lessons/audio/adult-d03/a-d03-tf-explanation.mp3",
          "durationMs": 20400,
          "say": "That price is a record of a trade that already happened — maybe seconds ago, maybe minutes ago. Your order shows up and meets whatever line exists right then. If you're buying in a hurry, you pay the ask, which is higher. If you're selling in a hurry, you get the bid, which is lower. On a big, busy stock that's pennies. On a quiet one, it really isn't."
        },
        "reask": {
          "url": "/lessons/audio/adult-d03/a-d03-tf-reask.mp3",
          "durationMs": 2480,
          "say": "Read it once more, then decide."
        }
      }
    },
    {
      "id": "a-d03-mc2",
      "type": "multiple_choice",
      "skill": "market_basics",
      "question": "Two stocks cost about the same. One has a 2-cent spread. The other has a 40-cent spread. What's most likely going on?",
      "options": [
        "The second company is worse",
        "The second one is more expensive",
        "Way fewer people are trading the second one, so both lines are thin and far apart",
        "The second one moved more today"
      ],
      "correctIndex": 2,
      "reinforce": "Yes — a spread is basically a headcount. Thousands of people haggling over Apple squeeze the gap down to a penny. Forty people haggling over a small company leave a canyon. And that canyon costs real money to anyone who has to cross it fast.",
      "explanation": "A spread is measuring the crowd around a stock, not the price of it.",
      "wrongFeedback": [
        {
          "kai": true,
          "text": "Tempting, but the spread is measuring the crowd, not the company. There are great small companies with wide spreads and pretty mediocre giant ones with penny spreads. All a spread tells you is how many people are standing in line — nothing about what they're lining up for. One more time."
        },
        {
          "text": "Both stocks cost about the same — that was the setup. The gap between the two lines isn't the price of the share."
        },
        null,
        {
          "text": "Close, and the two do hang out together — jumpy stocks usually have wider spreads. But it runs the other way round: thin trading causes both. Crowd size is the thing underneath."
        }
      ],
      "audio": {
        "prompt": {
          "url": "/lessons/audio/adult-d03/a-d03-mc2.mp3",
          "durationMs": 8480,
          "say": "Two stocks cost about the same. One has a 2-cent spread. The other has a 40-cent spread. What's most likely going on?"
        },
        "reinforce": {
          "url": "/lessons/audio/adult-d03/a-d03-mc2-reinforce.mp3",
          "durationMs": 14400,
          "say": "Yes — a spread is basically a headcount. Thousands of people haggling over Apple squeeze the gap down to a penny. Forty people haggling over a small company leave a canyon. And that canyon costs real money to anyone who has to cross it fast."
        },
        "explanation": {
          "url": "/lessons/audio/adult-d03/a-d03-mc2-explanation.mp3",
          "durationMs": 5760,
          "say": "A spread is measuring the crowd around a stock, not the price of it."
        },
        "wrong:0": {
          "url": "/lessons/audio/adult-d03/a-d03-mc2-wrong-0.mp3",
          "durationMs": 18160,
          "say": "Tempting, but the spread is measuring the crowd, not the company. There are great small companies with wide spreads and pretty mediocre giant ones with penny spreads. All a spread tells you is how many people are standing in line — nothing about what they're lining up for. One more time."
        },
        "wrong:1": {
          "url": "/lessons/audio/adult-d03/a-d03-mc2-wrong-1.mp3",
          "durationMs": 7280,
          "say": "Both stocks cost about the same — that was the setup. The gap between the two lines isn't the price of the share."
        },
        "wrong:3": {
          "url": "/lessons/audio/adult-d03/a-d03-mc2-wrong-3.mp3",
          "durationMs": 13520,
          "say": "Close, and the two do hang out together — jumpy stocks usually have wider spreads. But it runs the other way round: thin trading causes both. Crowd size is the thing underneath."
        },
        "reask": {
          "url": "/lessons/audio/adult-d03/a-d03-mc2-reask.mp3",
          "durationMs": 1520,
          "say": "Let's try that again."
        }
      }
    },
    {
      "id": "a-d03-rw",
      "type": "real_world",
      "skill": "market_basics",
      "action": "research_ticker",
      "ticker": "NKE",
      "company": "Nike",
      "prompt": "Go pull up a company you actually have an opinion about. Find the bid. Find the ask. Notice the gap. Then see where the last trade sits compared to both.",
      "cta": "Open the quote",
      "successText": "That gap is what it costs to be in a hurry. From now on, when someone says “the price”, you'll know which of those three numbers they mean — and whether it's the one you'd actually get.",
      "audio": {
        "prompt": {
          "url": "/lessons/audio/adult-d03/a-d03-rw.mp3",
          "durationMs": 10000,
          "say": "Go pull up a company you actually have an opinion about. Find the bid. Find the ask. Notice the gap. Then see where the last trade sits compared to both."
        },
        "success": {
          "url": "/lessons/audio/adult-d03/a-d03-rw-success.mp3",
          "durationMs": 13680,
          "say": "That gap is what it costs to be in a hurry. From now on, when someone says “the price”, you'll know which of those three numbers they mean — and whether it's the one you'd actually get."
        }
      }
    }
  ],
  "audio": {
    "intro": {
      "url": "/lessons/audio/adult-d03/lesson-intro.mp3",
      "durationMs": 12720,
      "say": "Most people picture a stock price like a price tag — somebody decided it, printed it, done. That picture is wrong, and it quietly costs people money. Give me seven minutes and you'll never look at a quote the same way."
    },
    "outro": {
      "url": "/lessons/audio/adult-d03/lesson-outro.mp3",
      "durationMs": 20960,
      "say": "You now know what's under every price move you'll ever see. Everything later in this course — where to put a stop, why a great quarter can tank a stock, what selling in pieces actually does — is just these two lines rearranging. Tomorrow we set up your workshop: which account to use, and why the answer depends on when you need the money, not what you're buying."
    }
  }
}
$json$::jsonb,
  est_minutes = 7,
  updated_at  = now()
where id = 'c0d3f1a0-0000-4000-8000-000000000003'
  and module_id = 'c0d3f1a0-0000-4000-8000-000000000002'
  and retired = false;
